### ISSUE TITLE
Clang-cl (on Windows) 5.0.1 64-bit bug

### ISSUE THREAD

**Issue by joelfrederico** [taocpp/PEGTL#101]
https://github.com/taocpp/PEGTL/blob/75eb3407b9cdd42936a498cc91d00402337a4a48/include/tao/pegtl/internal/peek_char.hpp#L25

https://github.com/taocpp/PEGTL/blob/75eb3407b9cdd42936a498cc91d00402337a4a48/include/tao/pegtl/contrib/parse_tree.hpp#L301

Clang-cl has an issue with these two lines. It gets confused and somehow thinks that the code is calling the constructor for the class it's in (`peek_char` and `remove_content`) and not the method of the variable `in` or `n`, respectively.

I don't know how you'd like to handle this (if at all). I'd appreciate it if the bug were fixed, but that is up to you of course. You could fix it in a few ways:

- Don't try to mark these functions `noexcept`.
- Rename the function or the class so that they're different (so clang-cl doesn't get confused).
- `#ifdef`s to not try to use `noexcept` for this compiler.

FYI, I've created a minimal test case that reproduces the bug, which I will submit to LLVM once they've given me an account. If you're interested, it's attached.

[main.cpp.txt](https://github.com/taocpp/PEGTL/files/1882215/main.cpp.txt)

**Comment by joelfrederico** [comment]
Or I can submit a PR if you have a preferred method for fixing it but can't test easily.

**Comment by joelfrederico** [comment]
Clang-cl bug report: https://bugs.llvm.org/show_bug.cgi?id=37030

**Comment by d-frey** [comment]
That is one weird "extension", but whatever... :)

I committed a fix which should be accepted by clang-cl (or regular clang with `-fms-extensions`, which is how I tested it). Please re-open if this does not solve the problem for you.

**Comment by d-frey** [comment]
FWIW, I added a CI job to test with `-fms-extensions`, hopefully it'll catch similar problems in the future.

**Comment by joelfrederico** [comment]
Very cool. I may not get to testing it for awhile but your method of fixing and testing is much better than mine. Thanks for addressing it!
