### ISSUE TITLE
Suggestion: Run CI on any branch

### ISSUE THREAD

**Issue by uilianries** [taocpp/PEGTL#113]
Hi!

I have the suggestion to run CI service (Travis and Appveyor) over all branches.

Both services have no limit (time) by month, so enjoy.

For feature branch would be nice to know if the branch is okay before to open a PR.

**Comment by d-frey** [comment]
I agree it would be helpful for the purpose you describe, the only drawback is that TravisCI and AppVeyor do have limits on concurrency, so too many changes in different branches will delay feedback for other branches.

Let's give it a shot anyways and see if causes any real problems. What I try to remember is to cancel planned jobs when I committed new changes to skip ahead.

**Comment by uilianries** [comment]
When the Bincrafters needs to build modular boost, for example, they report on slack channel to people cancel or avoid to use the CI. I used modular boost as reference because there are +100 packages involving it
