### ISSUE TITLE
Move Conan stuff to sub directory

### ISSUE THREAD

**Issue by uilianries** [taocpp/PEGTL#114]
To keep pegtl project clean, we should move build.py and test_package to a new sub-directory: conan

Conan solves the test directory by the names test or test_package, on same dir level, to use a custom path, the option -tf should be used.

Conan package tools has no support by env var to solve it, so we need to use the arguments.

**Comment by d-frey** [comment]
Thinking about it: Conan should consider two use-cases and treat both as first-class citizens:

1) out-of-source
2) in-source

The latter means that you want to be as unobtrusive as possible to existing repositories. Dreaming up an ideal: Just a single, top-level file called `.conan.yml`. Second best candidate: `.conan.py'. Third best option: `.conan/` as a top-level directory with a defined structure and all conan-specific stuff in it. That third option is probably most realistic right now.

**Comment by uilianries** [comment]
Good news @d-frey 

The tool used to build Conan in this project was released with custom path for the test folder just yesterday. So I'll update this issue later.

Your concern about project flavor is right. Conan just released the version 1.4.4 yesterday, and it brought the feature [workspaces](https://docs.conan.io/en/latest/developing_packages/workspaces.html). It's experimental and will be updated on next versions, but it shall be the feature that you asked.

Regards!
