### ISSUE TITLE
Include libpq as PEGTL requirement for Conan package

### ISSUE THREAD

**Issue by uilianries** [taocpp/PEGTL#122]
PEGTL Conan package does not solve libpq as a requirement, so the user should solve postgresql by itself. Conan is a package manager and it could solve such dependency.

Now we have libpq recipe on Bincrafters' repo: https://github.com/bincrafters/conan-libpq, however it is not on Conan center yet. The option IMO is wait for Conan admin review before to integrate with PEGTL.

**Comment by d-frey** [comment]
I'm pretty sure this issue belongs to taocpp/postgres, not taocpp/PEGTL ;)

**Comment by uilianries** [comment]
Oh boy! My fault! sorry about this, I'm going to move this issue now.
