### ISSUE TITLE
Compile Error with Visual Studio 2019 Preview (MSVC 19.20)

### ISSUE THREAD

**Issue by matbech** [taocpp/PEGTL#136]
Error:
28>C:\Projects\Libraries\taocpp-json\json\include\tao\json\external\pegtl\internal\duseltronik.hpp(48): error C2535: 'unknown-type tao::json_pegtl::internal::duseltronik<Rule,tao::json_pegtl::apply_mode::action,tao::json_pegtl::rewind_mode::required,Action,Control,tao::json_pegtl::dusel_mode::nothing>::match(Input &,States &&...)': member function already defined or declared
28>        with
28>        [
28>            Rule=tao::json::internal::pointer_grammar,
28>            Action=tao::json::internal::pointer_action,
28>            Control=tao::json_pegtl::normal
28>        ] (compiling source file ProtocolUI\Protocol\Controls\BoxAuthorizeControl.cpp)
28>C:\Projects\Libraries\taocpp-json\json\include\tao\json\external\pegtl\internal\duseltronik.hpp(39): note: see declaration of 'tao::json_pegtl::internal::duseltronik<Rule,tao::json_pegtl::apply_mode::action,tao::json_pegtl::rewind_mode::required,Action,Control,tao::json_pegtl::dusel_mode::nothing>::match'
28>        with
28>        [
28>            Rule=tao::json::internal::pointer_grammar,
28>            Action=tao::json::internal::pointer_action,
28>            Control=tao::json_pegtl::normal
28>        ] (compiling source file ProtocolUI\Protocol\Controls\BoxAuthorizeControl.cpp)
28>C:\Projects\Libraries\taocpp-json\json\include\tao\json\external\pegtl\internal\duseltronik.hpp(67): note: see reference to class template instantiation 'tao::json_pegtl::internal::duseltronik<Rule,tao::json_pegtl::apply_mode::action,tao::json_pegtl::rewind_mode::required,Action,Control,tao::json_pegtl::dusel_mode::nothing>' being compiled
28>        with
28>        [
28>            Rule=tao::json::internal::pointer_grammar,
28>            Action=tao::json::internal::pointer_action,
28>            Control=tao::json_pegtl::normal
28>        ] (compiling source file ProtocolUI\Protocol\Controls\BoxAuthorizeControl.cpp)

Triggered by:
```
            template< typename Input, typename... States >
            [[nodiscard]] static auto match( Input& in, States&&... st )
               -> decltype( (void)Rule::template match< A, M, Action, Control >( in, st... ), bool() )
            {
               return Rule::template match< A, M, Action, Control >( in, st... );
            }

            template< typename Input, typename... States >
            [[nodiscard]] static auto match( Input& in, States&&... /*unused*/ )
               -> decltype( (void)Rule::match( in ), bool() )
            {
               return Rule::match( in );
            }
```

**Comment by d-frey** [comment]
This seems to be (yet another) problem with MSVC, unless you defined your own `match` method that (accidentally) matches both signatures. If that is not the case, and given that you are using a Preview version, please file a bug report with Microsoft.

**Comment by matbech** [comment]
I have reported the issue here:
https://developercommunity.visualstudio.com/content/problem/403244/compile-error-with-pegtl.html

**Comment by d-frey** [comment]
Hm, OK. Does changing the second template parameter list to

    template< typename Input, typename... States, int = 1 >

help?

**Comment by matbech** [comment]
Yes, this works as a workaround. Thank you.

**Comment by d-frey** [comment]
OK. If you can confirm that it was working with VS 2017, could you please let MS know that this is a regression? Hopefully, that will increase our chances of getting it fixed. Showing them the work-around might also help to narrow down the area where they need to work on, probably "Expression SFINAE" (not sure if they even tried to implement it).

**Comment by matbech** [comment]
Yes, it was working with VS 2017. It might be better if you - as the author of the library - is posting the workaround here: https://developercommunity.visualstudio.com/content/problem/403244/compile-error-with-pegtl.html
Thanks.

**Comment by d-frey** [comment]
@matbech I've seen that VS2019 has been released. Did they fix the regression?

**Comment by matbech** [comment]
Unfortunately, no. It is still the same in VS2019 GA.

**Comment by d-frey** [comment]
It's sad that they broke it again. Could you do us a favor and check that the fix works? Also if you don't mind, could you also check if the 2.x branch works with VS2019? We'd like to release them soon and it would be unfortunate if they break with VS2019. TIA.

**Comment by matbech** [comment]
The fix works. I'm only using the master branch (version 3.x) of PEGTL as part of taoJSON.
