### ISSUE TITLE
Handle correcly state with pegtl grammar

### ISSUE THREAD

**Issue by alangab** [taocpp/PEGTL#139]
I'm very new to peg and pegtl, so probably I'm missing something. I have a grammar very similar to the following one:

```
using namespace tao::pegtl;

struct A : one<'A'> { };
struct B : one<'B'> { };

struct comp : seq<plus<sor<seq<A, B>, A>>,eof> { };

template< typename Rule >
struct test_action : nothing< Rule > {};

template<>
struct test_action<A>
{
    template< typename Input >
    static void apply(const Input& in)
    {
        std::cout << "A";
    }
};

template<>
struct test_action<B>
{
    template< typename Input >
    static void apply(const Input& in)
    {
        std::cout << "B";
    }
};

void test()
{
    parse< comp, test_action >(memory_input("AAB", ""));
}

```
he parse works great, but there is too many activation of test_action::apply. The program outputs "AAAB", because, if I understand well, the parse tries the first alternative (AB) for the first character and fails, then proceeds with the other (A). But even if it "rewinds", it always call test_action::apply. What is the correct way to handle this situation? My intent is to output "AAB", possibly without complicate the grammar.

**Comment by nlyan** [comment]
Any parser that "rewinds", like those generated by PEGTL, will have to 'undo' any state modifications it made on the failed branch. The way PEGTL allows you to do this is with the "control class", which gives you callback when a parse rule starts to match and when it matches either successfully or not, but it's up to you as the programmer to put a solution together.

Imho, for complex grammars where backtracking is likely and easy to miss, the best thing to do is make your parser construct a parse tree, which is easy to fix when it backtracks using simple push and pop operations  (e.g. resulting in removing the first 'A' node), and then pass that tree to the rest of your program. Constructing a parse tree inside a backtracking PEGTL is a simple and generic algorithm that works for any grammar.

**Comment by d-frey** [comment]
To add: The PEGTL does have out-of-the-box support for generating a parse-tree (and even apply some transformations towards an AST on-the-fly), have a look at the examples.

Parse-tree generation is thereby a two-pass approach, you first generate the parse-tree from the input, then you use the (now stable) parse-tree to do whatever you want with it. If your application does not parse enormous amounts of data, this is usually not a performance issue and you get rid of all backtracking issues.

**Comment by alangab** [comment]
Thank you for your support.  I wrote a couple of solution following your suggestions:

- avoid backtracking in rules with attached actions:
```
namespace solution_a {

	using namespace tao::pegtl;

	struct A : one<'A'> { };
	struct B : one<'B'> { };

	struct real_A : A {};
	struct real_AB : seq<A, B> {};

	struct comp : seq<plus<sor<real_AB, real_A>>,eof> { };

	template< typename Rule >
	struct test_action : nothing< Rule > {};

	template<>
	struct test_action<real_A>
	{
		template< typename Input >
		static void apply(const Input& in)
		{
			std::cout << "A";
		}
	};

	template<>
	struct test_action<real_AB>
	{
		template< typename Input >
		static void apply(const Input& in)
		{
			std::cout << "AB";
		}
	};



	void test()
	{
		parse< comp, test_action >(memory_input("AAB", ""));
	}
```
- build a parse tree:

```
namespace solution_b {

	using namespace tao::pegtl;

	struct A : one<'A'> { };
	struct B : one<'B'> { };

	
	struct comp : seq<plus<sor<seq<A, B>, A>>, eof> { };

	template< typename Rule >
	struct test_action : nothing< Rule > {};


	void test()
	{
		auto root = parse_tree::parse<comp>(memory_input("AAB", ""));
	}

}

```

**Comment by alangab** [comment]
Thank you very much!

**Comment by ColinH** [comment]
You're welcome! For the record, another possibility, if not particularly elegant, is to use the (infinite) lookahead feature of PEGs.

With something like `seq< at< foo >, foo >`, the first `foo` will attempt to match with actions disabled, and only if that succeeded will `foo` be matched again, this time with actions enabled.

**Comment by nlyan** [comment]
I took the last approach suggested by @ColinH in one of my own recent projects.

I had a grammar matching a "key = value" type string where the right-hand side (the 'value') had a more elaborate grammar for a particular 'key' string. These pairs was also handled by a generic option handling sub-grammar placed at the end of a `sor<>` rule, but this wasn't being triggered for a particular key (e.g. "foosize = ") because it happened to be the prefix of the specialized one (e.g. "foo = "), resulting in the parser accepting "foo", then looking for the " = " separator while looking at "size".

Here's a cut out of my solution:

```cpp
template <typename... Rules>
using lookahead = seq<at<Rules...>, Rules...>;

template <typename Key, typename Value,
          typename Separator = option_value_separator>
struct option : seq<lookahead<Key, Separator>, must<Value>> {};
```
There's a degree of black magic to creating PEG grammars.
