### ISSUE TITLE
Question: Using PEGTL without RTTI

### ISSUE THREAD

**Issue by nshcat** [taocpp/PEGTL#146]
Hello,
as part of my thesis I was planning to use the PEGTL inside of the codebase of `clang`, which creates some issues since RTTI is disabled in that codebase and is non-trivial to turn on.

I don't use the `parse_tree`  functionality from the PEGTL, so the only thing that does not compile seems to be the demangling routines defined in `/internal/demangle.hpp`. How essential are those to the inner workings of the PEGTL?

Thanks a lot in advance

**Comment by ColinH** [comment]
The demangle functionality is only used for debugging and error messages. To prevent the core library from both using `demangle()` and throwing exceptions, you can create your own Control class (class template `my_control< Rule >` that inherits from `pegtl::normal< Rule >`) that redefines the `raise()` function to do whatever you want it to do without calling `demangle()` (and possibly without throwing exceptions). Does this help?

**Comment by nshcat** [comment]
Thank you a lot, this certainly helped!
