### ISSUE TITLE
lgtm static analysis

### ISSUE THREAD

**Issue by GillianGrayson** [taocpp/PEGTL#159]
Hi!

If I understood correctly your project is not really analyzed on lgtm.
All your recent commints have status: 
"We were unable to analyze this commit" as show on attached picture.
![image](https://user-images.githubusercontent.com/26212004/55155223-dfd0df80-5167-11e9-81e7-386ffb17e067.png)
I have almost the same issue with lgtm and my very small header-only lib.
Maybe you can fix this issue for your project and tell me how you did it.

Thank you!

**Comment by d-frey** [comment]
It looks like they are running into a timeout or into some other resource constraint. If you scroll down for the PEGTL, there were cases where it worked (and this is presumably where their metrics are from), but most builds/analyse-runs seem to fail now. Recent builds were cancelled at about 13%.

**Comment by d-frey** [comment]
I created an issue with LGTM: https://discuss.lgtm.com/t/extraction-timed-out-after-2-minutes/1963

**Comment by d-frey** [comment]
It seems to be working now, the LGTM issue will track whether they actually fixed the parser or if a change in our code "fixed" it. Anyways, the issue from the PEGTL's POV is now resolved.
