### ISSUE TITLE
Add CI tests for Android

### ISSUE THREAD

**Issue by d-frey** [taocpp/PEGTL#161]
We'd appreciate a PR to add CI tests for Android. Ideally, we are looking for a maintainer that also takes care of maintenance of those jobs and Android support in general.

**Comment by Bjoe** [comment]
@d-frey Hi, I didn't see that you are need help for android ....

I can help and also maintain this .... I have a quite good knowledge about android NDK cmake builds ... (see also my bug report in android NDK and cmake ;-) )
For travis in the past I downloaded for every build the android SDK/NDK, you already know I think. I working for a solution to have a already setup docker with the newest SDK/NDK.

Give me some time, I will create a pull request if I'm done with that. We can also talk togheter at the next C++ meetup :-)

**Comment by d-frey** [comment]
Thanks Jörg, I know you are well capable of helping out with the Android builds as you already helped setting them up in the past :) Just for the record: I wasn't unhappy with them, the build speed wasn't the issue why I removed them - of course any improvement is welcome in that area. But the reason for the removal was the switch to C++17 and I couldn't figure out how to update to a new-enough version of Android that has a compiler and standard library version that supports all the C++17 stuff we need.

I'm looking forward to seeing a PR from you and, of course, seeing you in Düsseldorf again! If you are interested and your time permits, we'd be more than happy to make you the official taocpp Android maintainer :)

**Comment by d-frey** [comment]
Oh, and we are still maintaining the 2.x branch for now that is C++11-based. I think the problem there was the switch to xenial that TravisCI? I don't remember exactly, put a PR there would also be welcome if you have time :)

**Comment by Bjoe** [comment]
> Oh, and we are still maintaining the 2.x branch for now that is C++11-based. I think the problem there was the switch to xenial that TravisCI? I don't remember exactly, put a PR there would also be welcome if you have time :)

Ok, I will do this. Give me somedays, then I create a PR ....

BTW. it compiles for [Android NDK r17 / API 24 / arm64-v8a / Clang / c++14 support / libc++ static](https://travis-ci.org/Bjoe/hunter/jobs/549787290) :-)

**Comment by Bjoe** [comment]
Some WIP information ... [first working android test build ](https://travis-ci.org/Bjoe/PEGTL/jobs/553776912) :-)....

**Comment by Bjoe** [comment]
First version are done #178
