### ISSUE TITLE
discard_input action unexpected behavior 

### ISSUE THREAD

**Issue by Shaheen47** [taocpp/PEGTL#170]
Hello,
I am trying to implement a  parser for RDF turtle language.
everything worked well for the file and string input and now I am implementing a stream input parser.
let's say for example I want to discard input to empty the buffer after each time the rule "statement" is parsed. therefore I defined an action for this rule as follows:

        template<>
        struct action<TurtlePegtlGrammer::statement>: tao::pegtl::discard_input{
            template<typename Input>
            static void apply(const Input &in, TurtlePegtlStates::State<> &state) {
            }
        };

after defining this action.When I call the parse function 

parse<Gram, TurtlePegtlActions::action>(istream_input(stream, defaultBufferSize, filename), state);

no action occurs and it acts as it is parsing without going through the actions.
Is there anything that I misunderstood in applying the stream input?

Thanks very much in advance.

**Comment by d-frey** [comment]
I think I found the problem, please check if master still fails to call the action.

**Comment by Shaheen47** [comment]
It is working now . 
Thanks.
