### ISSUE TITLE
Warnings with -Wconversion

### ISSUE THREAD

**Issue by 0x8000-0000** [taocpp/PEGTL#182]
Building a project with -Wconversion -Werror, I stumbled upon these four warnings in the PEGTL library:

`.../external/PEGTL/include/tao/pegtl/internal/istring.hpp:81:76: error: conversion from ‘long unsigned int’ to ‘unsigned int’ may change value [-Werror=conversion]
             using analyze_t = analysis::counted< analysis::rule_type::any, sizeof...( Cs ) >;
                                                                            ^~~~~~~~~~~~~~~

.../external/PEGTL/include/tao/pegtl/internal/string.hpp:42:76: error: conversion from ‘long unsigned int’ to ‘unsigned int’ may change value [-Werror=conversion]
             using analyze_t = analysis::counted< analysis::rule_type::any, sizeof...( Cs ) >;
                                                                            ^~~~~~~~~~~~~~~

.../external/PEGTL/include/tao/pegtl/internal/endian.hpp: In function ‘N tao::pegtl::internal::h_to_be(N)’:
.../external/PEGTL/include/tao/pegtl/internal/endian.hpp:27:39: error: conversion from ‘long unsigned int’ to ‘unsigned int’ may change value [-Werror=conversion]
             return N( to_and_from_be< sizeof( N ) >::convert( n ) );
                                       ^~~~~~~~~~~
.../external/PEGTL/include/tao/pegtl/internal/endian.hpp: In function ‘N tao::pegtl::internal::h_to_le(N)’:
.../external/PEGTL/include/tao/pegtl/internal/endian.hpp:47:39: error: conversion from ‘long unsigned int’ to ‘unsigned int’ may change value [-Werror=conversion]
             return N( to_and_from_le< sizeof( N ) >::convert( n ) );
                                       ^~~~~~~~~~~`

This is with GCC 8.3 on Debian x86-64.

**Comment by d-frey** [comment]
I found some more when I added the option to our `Makefile`, I'll fix them soon. Thanks for reporting!

**Comment by d-frey** [comment]
I reverted some changes I made and generally disabled testing with `-Wconversion`. It was producing too much noise (especially with Clang) and this would lead to worse code than before (or multiple `#pragma disable ...` sections). I'm sorry, but there probably is a good reason why `-Wconversion` is *not* included in `-Wall -Wextra`. This issues you found initially are still fixed, though. I hope this is OK for you, let me know if you see a better way of handling the situation.

**Comment by d-frey** [comment]
Sorry for the delay, and feel free to send PRs. The problem is that I don't feel that there is anything wrong with the code at hand, so I think it might be helpful if you could first outline with one or two examples how you'd like to "fix" the code. Or would you just disable the warning with pragmas?

**Comment by d-frey** [comment]
Did you have time to work on this issue or is it no longer relevant?

**Comment by 0x8000-0000** [comment]
I think the warnings are still there but that project is dormant for me right now. Feel free to close.

**Comment by d-frey** [comment]
OK, I think we fixed *some* of those warnings, but fixing all of them doesn't seem practical right now. Thanks anyways!
