### ISSUE TITLE
test case pegtl-test-demangle fails

### ISSUE THREAD

**Issue by yurivict** [taocpp/PEGTL#189]
```
The following tests FAILED:
	 38 - pegtl-test-demangle (Failed)
```

```
$ ./work/.build/src/test/pegtl/pegtl-test-demangle
pegtl: unit test assert [ a == s ] failed in line [ 22 ] file [ /usr/ports/devel/pegtl/work/PEGTL-2.8.1/src/test/pegtl/demangle.cpp ]
pegtl: unit test ./work/.build/src/test/pegtl/pegtl-test-demangle failed 1
```

OS: FreeBSD 12 amd64
clang-8

**Comment by ColinH** [comment]
Could you please change the testcase to print the two values before comparing them and show us the output? Neither of us uses FreeBSD, so we can't easily replicate the issue to see what exactly is going on.

**Comment by yurivict** [comment]
```
$ ./work/.build/src/test/pegtl/pegtl-test-demangle
a=short
s=something that can't be demangled
pegtl: unit test assert [ a == s ] failed in line [ 24 ] file [ /usr/ports/devel/pegtl/work/PEGTL-2.8.1/src/test/pegtl/demangle.cpp ]
pegtl: unit test ./work/.build/src/test/pegtl/pegtl-test-demangle failed 1
```

**Comment by ColinH** [comment]
We don't quite understand what's going on here, and we don't have ready access to a FreeBSD machine, could you please also show us the output of `build/src/test/pegtl/tester`? That might give a clue as to which implementation in `include/tao/pegtl/internal/demangle.hpp` is actually used; it might not be the one that we are expecting.

**Comment by ColinH** [comment]
@yurivict Any new information?

**Comment by yurivict** [comment]
It still fails.

**Comment by d-frey** [comment]
@yurivict Could you also provide us with the information Colin asked for? It's quite difficult for us to diagnose the problem, after all it is your environment that produces the error. Without help from your side, I'm afraid we can't really do much about it.
