### ISSUE TITLE
Feature request: support for custom allocator or pointer wrapper for parse_tree

### ISSUE THREAD

**Issue by toddlipcon** [taocpp/PEGTL#192]
In my parser which uses parse_tree, I found that most of the CPU cycles are going to allocation, deallocation, and cache misses due to the parse tree AST nodes being allocated far from each other in memory. I'd like to use an arena allocator instead, so that allocations are done by "bump-the-pointer" and all deallocations can happen in batch when the parse tree is no longer needed.

Currently, parse_tree enforces the use of std::unique_ptr and doesn't allow customization of the creation or deletion of nodes. It would be great to have a customization point to be able to override the use of std::unique_ptr<> to use a custom deleter instance. It's possible that this can be done by specializing std::default_delete<node> but seems like a cleaner solution might be available (that solution would need to rely on threadlocal storage to pass in the pointer of the arena)

**Comment by toddlipcon** [comment]
I found I was able to get some small benefit by specializing parse_tree::internal::state<Node> for my node type, so that pop_back would return nodes to a pool, and emplace_back would reuse them when possible, but still difficult to get to the full bump allocator.

**Comment by skyrich62** [comment]
I think you started off with a good idea there.  If you also create your own operator new for your node, you'd have the bump allocator.    You could also provide your own version of basic_node, (with the same interface that parse_tree::basic_node has.  This way you'd have std::unique_ptr<basic_node, YourDeleterHere> in the trees, and std::make_unique would just call your operator new.

**Comment by d-frey** [comment]
I think you don't need your own `basic_node`, just your own `node`. Overloading `operator new` and `operator delete` for your node should give you all you need. I modified the parse tree example accordingly, please check if that idea works for you.

**Comment by d-frey** [comment]
Any feedback on the above idea and the modified parse tree example? Can we close this issue?
