### ISSUE TITLE
default format of error message (byte in line)

### ISSUE THREAD

**Issue by wojdyr** [taocpp/PEGTL#204]
I'm a happy user of PEGTL.
Someone pointed to me that the in-line position in error message in my parser (which is a default PEGTL position formatting) is 0-based. For example, when the error is at the first byte of the file it is:

    file:1:0(0)

while it may be more conventional to use 1-based number.
For example, GCC and Clang would print it as:

    file:1:1

I know it's just bikeshedding, so feel free to close this issue.

**Comment by d-frey** [comment]
Both Colin and me are Emacs users, and Emacs counts the columns from 0.

OTOH, I just checked and vi, gedit, eclipse, vscode, ... count from 1. Plus, as you mentioned, the compilers. It seems Emacs really is the exception here. @ColinH What do you think? Should we change it?

**Comment by ColinH** [comment]
Well, yes, if everybody else is starting at 1 it might be prudent to change it. (And make it configurable? 8-)

**Comment by d-frey** [comment]
So let's make it configurable. And to be on the safe side, let's allow a floating point value and... 🤪

OK, just kidding... I'll change it to 1, though.

**Comment by d-frey** [comment]
I even found the switch for emacs to count columns 1-based. 😁
