### ISSUE TITLE
`contrib/integer.hpp` should include `<numeric_limits>`

### ISSUE THREAD

**Issue by le-migou** [taocpp/PEGTL#232]
#include <tao/pegtl/contrib/integer.hpp>
    int main () {}

Gives

    In file included from a.cpp:1:
    ../../../external/taocpp/pegtl/include/tao/pegtl/contrib/integer.hpp:63:60: error: ‘numeric_limits’ is not a member of ‘std’
       63 |       template< typename Integer, Integer Maximum = ( std::numeric_limits< Integer >::max )() >

**Comment by le-migou** [comment]
Sorry, I meant <limits> of course.

**Comment by d-frey** [comment]
But we *do* include `<limits>`. Can you dig deeper and figure out what is actually going on on your system?

**Comment by le-migou** [comment]
Sorry, my bad I was really too far behind !

**Comment by ColinH** [comment]
No problem, thanks for reporting, even if it turned out to be a non-issue :-)
