### ISSUE TITLE
Target exporting error when using `add_subdirectory`

### ISSUE THREAD

**Issue by anand-bala** [taocpp/PEGTL#255]
Hey everyone. First of all, I love this project!

I am trying to write a parser for a custom, Lisp-like language and I am using `add_subdirectory(pegtl)` via CMake's `FetchContent` module. When I do that, I am getting the following error:

```
CMake Error in CMakeLists.txt:
  export called with target "signaltl" which requires target "pegtl" that is
  not in any export set.
```
I suspect it is because you are missing a call to CMake's [`export`](https://cmake.org/cmake/help/latest/command/export.html) command.

Happy New Year!

Edit: The project I am working on is [anand-bala/signal-temporal-logic](https://github.com/anand-bala/signal-temporal-logic/tree/parser) in the `parser` branch.

**Comment by anand-bala** [comment]
I used the following workaround to fix it for my case:

```
      export(
        EXPORT pegtl-targets
        FILE ${pegtl_BINARY_DIR}/pegtl-targets.cmake
        NAMESPACE taocpp::
      )
```

**Comment by d-frey** [comment]
Thank you for the kind words, happy new year to you!

Can you confirm that the fix works?

**Comment by anand-bala** [comment]
This works perfectly! Thanks!
