### ISSUE TITLE
How to include PEGTL in a cmake project?

### ISSUE THREAD

**Issue by createyourpersonalaccount** [taocpp/PEGTL#265]
Hello,

I'd like to include PEGTL in a project I am working with. (By the way, I love PEGTL! It's great).

So far I am doing it using FetchContent, for example in my top-level `CMakeLists.txt` I have,

    include(FetchContent)
    FetchContent_Declare(
      pegtl
      GIT_REPOSITORY https://github.com/taocpp/PEGTL.git
      GIT_TAG        7d039707cf835cea63daa78a717e18fcc5bcf95b # release-3.2.0
      )
    FetchContent_MakeAvailable(pegtl)

but what I'd like is to have the build work offline too, in case the user has installed PEGTL in their system. I see that debian has `tao-pegtl-dev` for example. How can I do this? Or does PEGTL not provide an installation module like that?

**Comment by thoism** [comment]
https://github.com/taocpp/PEGTL/blob/master/doc/Installing-and-Using.md#find_package

**Comment by createyourpersonalaccount** [comment]
Thank you, I overlooked this item in the document!

**Comment by thoism** [comment]
> Thank you, I overlooked this item in the document!

No worries! Έγινε φίλε!
