### ISSUE TITLE
Help writing a grammar for SPARQL

### ISSUE THREAD

**Issue by kelvinhammond** [taocpp/PEGTL#271]
Hello,

I'm trying to write a grammar for SPARQL and in the [spec](https://www.w3.org/TR/sparql11-query/#rPN_PREFIX) for [PN_PREFIX](https://www.w3.org/TR/sparql11-query/#rPN_PREFIX).

How would I match the following in PEGTL?
`1...2...3`, a regular expression for this would be `\d((\d|\.)*\d)?` where the first is always a digit, any number of digits or dots but always ending in a digit. After this other things may be matched or it could be the end.

**Comment by d-frey** [comment]
Given the definition in the form of a CFG is

```
PN_PREFIX ::= PN_CHARS_BASE ((PN_CHARS\|'.')* PN_CHARS)?
```

it is a little bit tricky to translate to a PEG, as PEGs are greedy, so you could reformulate that to

```
PN_PREFIX ::= PN_CHARS_BASE ('.'* PN_CHARS)*
```

which works both as a CFG and a PEG (althougt the PEG is still more greedy than the CFG, but that hopefully won't matter here).

This then translates to the PEGTL like this:

```
// given the other rules...
struct pn_chars_base;
struct pn_chars;

struct pn_prefix : seq< pn_chars_base, star< star< one< '.' > >, pn_chars > > {};
```

**Comment by d-frey** [comment]
I assume the issue is resolved, feel free to reopen if it is not.
