### ISSUE TITLE
Include Statements

### ISSUE THREAD

**Issue by ingo-loehken** [taocpp/PEGTL#282]
I would like propose to change include statements to root-based notation.

in *pegtl/contrib/icu/utf8.hpp* from 
```cpp
#include "../../utf8.hpp"
```

to
```cpp
#include <pegtl/utf8.hpp>
```

to ease relocation and unify with common notation of foreign components.

**Comment by d-frey** [comment]
Please see #10, where we explained why we are using relative includes.

**Comment by ingo-loehken** [comment]
Thanks. 

I ask myself the question: What is the reason for (i.e. boost, nlohman an others) to use adressing from a well-defined root and system include style, instead using relative adressing an user-include style ?

The only drawback I see from using a well defined root (i.e. pegtl or tao/pegtl) is that this one might collide with another root of the same name. But all other includes remain unaffected.
