### ISSUE TITLE
custom ostream redirection

### ISSUE THREAD

**Issue by mgood7123** [taocpp/PEGTL#284]
is it possible to output to a custom stream instead of std::cout ?

for example to a custom class with appropriate << operators for stream output

such as an ofstream (file output stream) or a custom logging class

**Comment by d-frey** [comment]
Output what? We currently use std::cout in our examples and tests, but the library itself never outputs to std::cout.

**Comment by mgood7123** [comment]
> Output what? We currently use std::cout in our examples and tests, but the library itself never outputs to std::cout.

oh ok :)

**Comment by mgood7123** [comment]
wait what about trace.hpp ?

**Comment by d-frey** [comment]
Ah, Trace. Yes, although technically that's `std::cerr`, not `std::cout`. But I see your point.

If you want to plug the trace into your own logging system, you probably want a different formatting (and no colors?). For a specific use-case, you also don't need the traits. So *our* tracer (which is in contrib for a reason) simply works as an example/blueprint for *your* tracer. You can write your own tracer which outputs any format to any target, just copy-paste the tracer and adapt it as needed. All the interfaces that the tracer uses are public, documented interfaces.

(The Analyzer also outputs to `std::cerr`, but that is also something you probably won't need to change)
