### ISSUE TITLE
at_one removal still referenced in docs

### ISSUE THREAD

**Issue by mgood7123** [taocpp/PEGTL#287]
1.0.0 removes `at_one` but `at_one` is still referred to in https://github.com/taocpp/PEGTL/blob/main/doc/Performance-Notes.md

`we noticed that the combination at< one< ... > > could be combined into an optimised at_one< ... > rule: Instead of one< ... > advancing the input, and at< one< ... > > rewinding, the combined rule would omit both the advancing and the rewinding.`

**Comment by d-frey** [comment]
You mean `at_one`, not `one_at`, right? And the doc explains why it was removed, so I don't really see the issue here.

**Comment by mgood7123** [comment]
yea, but https://github.com/taocpp/PEGTL/blob/main/doc/Performance-Notes.md references it as if it still exists in the api

**Comment by d-frey** [comment]
I've added a hint to the docs.

**Comment by mgood7123** [comment]
to clarify is it talking about a version of `at_one` that has been implemented in the JSON_LIBRARY or a version that was present in PEGTL itself?

**Comment by d-frey** [comment]
I think there was a version in the PEGTL, it was added for the JSON library IIRC. But it doesn't matter: The optimizer is smart enough to make it superfluous.

**Comment by mgood7123** [comment]
alright :)
