### ISSUE TITLE
dynamic input modification

### ISSUE THREAD

**Issue by mgood7123** [taocpp/PEGTL#290]
is it possible to dynamically modify the input?

for example

upon parsing PARSE_ERROR the input will be prepended by `int int`

INPUT: "PARSE_ERROR foo;"
INPUT: " foo;"
apply action
INPUT: "int int foo;"

for example, if the parser is in the middle of a grammar statement it might improve performance as the entire grammar does not need to be executed twice

**Comment by ColinH** [comment]
We have, so far, not considered the possibility of modifying an input while parsing it.

**Comment by d-frey** [comment]
I don't think this fits well with the rest of the PEGTL, as backtracking would become extremely "interesting".

**Comment by mgood7123** [comment]
> I don't think this fits well with the rest of the PEGTL, as backtracking would become extremely "interesting".

because changes to the input stream would need to be rolled-back ?

**Comment by d-frey** [comment]
There are more issues, like other rules storing non-owning views to the input, which now may change at any time. Or buffered input, mmapped files (where the input is read-only), broken invariants from custom rules, ... - so no, modifying the input in a parser library is a no-go for me. When we refactor the input layer, we might consider generating one input as a re-write of another input (think tokenization), but still both will then be non-modifiable by the respective grammars.

**Comment by mgood7123** [comment]
> There are more issues, like other rules storing non-owning views to the input, which now may change at any time. Or buffered input, mmapped files (where the input is read-only), broken invariants from custom rules, ... - so no, modifying the input in a parser library is a no-go for me. When we refactor the input layer, we might consider generating one input as a re-write of another input (think tokenization), but still both will then be non-modifiable by the respective grammars.

fair enough :)
