### ISSUE TITLE
raise_string rule?

### ISSUE THREAD

**Issue by mgood7123** [taocpp/PEGTL#292]
`TAO_PEGTL_RAISE_STRING("My error string")`

equivilant to `TAO_PEGTL_STRING` except it raises as a `parse_error` instead of matching as a string

```C++
#define TAO_PEGTL_RAISE_STRING( x ) \
   TAO_PEGTL_INTERNAL_STRING( TAO_PEGTL_NAMESPACE::raise_string, x )

namespace TAO_PEGTL_NAMESPACE::internal
{
   template< char... Cs >
   struct raise_string
   {
      using rule_t = raise_string;
      using subs_t = empty_list;

      template< int Eol >
      static constexpr bool can_match_eol = one< result_on_found::success, peek_char, Cs... >::template can_match_eol< Eol >;

      template< typename ParseInput >
      [[nodiscard]] static bool match( ParseInput& in )
      {
        std::string s = { Cs... };
        throw TAO_PEGTL_NAMESPACE::parse_error(s, in);
      }
   };

   template< char... Cs >
   inline constexpr bool enable_control< raise_string< Cs... > > = false;
}

namespace TAO_PEGTL_NAMESPACE
{
   template< char... Cs > struct raise_string : internal::raise_string< Cs... > {};
}
```

small usage

```C++
using namespace tao;

struct brace;

// matches [ ... ]
// raises if unbalanced [ is encountered
struct brace : pegtl::seq<
    pegtl::one<'['>,
    body_or_brace,
    pegtl::sor<
      pegtl::one<']'>,
      TAO_PEGTL_RAISE_STRING("Expected closing brace to balance opening brace")
    >
> {};
```

**Comment by ColinH** [comment]
@d-frey This goes a bit against our recent style of non-intrusive exception throwing (from a grammar p.o.v.) but since we aren't forbidding the other style and want to leave it as a choice I don't see why this couldn't go into contrib?

**Comment by mgood7123** [comment]
> @d-frey This goes a bit against our recent style of non-intrusive exception throwing (from a grammar p.o.v.) but since we aren't forbidding the other style and want to leave it as a choice I don't see why this couldn't go into contrib?

what is non-intrusive exception throwing?

**Comment by ColinH** [comment]
Non-intrusive means that both the choice when to throw an exception and the content of the exceptions are not embedded in the grammar. Look at `src/examples/pegtl/json_errors.hpp` and how it is used to see one example of how that can be achieved.

**Comment by d-frey** [comment]
There are a few issues with this. First, we want to throw these exceptions through the control class template. Next, we usually don't want to mix this into the grammar itself. As Colin already mentioned, `src/examples/pegtl/json_errors.hpp` shows an alternative. That said, I can think of some improvements on how you can specify those error messages. Maybe we can put a more convenient customization point for the error messages in the standard control class template? Or the rules themselves? I'll play with some ideas...

**Comment by d-frey** [comment]
Also, `can_match_eol` is always `false`, as the rule doesn't match anything :)

**Comment by mgood7123** [comment]
how would i instead raise a global/local error instead of throwing an exception?

**Comment by ColinH** [comment]
There is a customisation point in the `Control` class, the `raise()` function, where the details of which exception to throw (or do something else when compiling without exceptions) can be changed.

**Comment by mgood7123** [comment]
> It's not about not throwing an exception, it's about how. There is a customisation point in the `Control` class, the `raise()` function, where the details of which exception to throw (or do something else when compiling without exceptions) can be changed.

hmm ok

**Comment by d-frey** [comment]
I have something cooked up that should work similarly to what you suggested, but it doesn't bypass the control class and therefore works with tracers/coverage/etc. control classes. I'll do a review with Colin when time permits and hopefully it'll land in the repository soon.

**Comment by mgood7123** [comment]
> I have something cooked up that should work similarly to what you suggested, but it doesn't bypass the control class and therefore works with tracers/coverage/etc. control classes. I'll do a review with Colin when time permits and hopefully it'll land in the repository soon.
> […](#)
> On 17. Dec 2021, at 12:29, mgood7123 ***@***.***> wrote: ﻿ It's not about not throwing an exception, it's about how. There is a customisation point in the Control class, the raise() function, where the details of which exception to throw (or do something else when compiling without exceptions) can be changed. hmm ok — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

nice :)

**Comment by d-frey** [comment]
After reviewing the changes with @ColinH, I pushed them to GitHub. See if this works for you and let us know if you have any more questions. And thanks for the idea :)

**Comment by mgood7123** [comment]
> After reviewing the changes with @ColinH, I pushed them to GitHub. See if this works for you and let us know if you have any more questions. And thanks for the idea :)

alright :)
