### ISSUE TITLE
Provide a nuget Package

### ISSUE THREAD

**Issue by domi516** [taocpp/PEGTL#293]
### Discussed in https://github.com/taocpp/PEGTL/discussions/291

<div type='discussions-op-text'>

<sup>Originally posted by **domi516** December 15, 2021</sup>
Hi,

first of all: Thank u so much for that awesome library :)

I've just created a local nuget Package for the current Pegtl-Version 3.2.2.
I wanted to get in touch with you and ask if it would be possible to provide this on [Nuget.org](https://www.nuget.org)?
I have the feeling, that there are very less native (c++) nuget-libraries and this is the point where we can start to change this and make C++ more and more attractive for people.
Another benefit for u is, that your library has one more possibility to reach and help lots of people.

So if u're ok with the provision of your library on [Nuget.org](https://www.nuget.org), please let me know.

If you are fine with this, I think there will be two options to do that:

1. I upload the package at nuget.org and mention u (Daniel Frey & Dr. Colin Hirsch) as authors and owners.
2. I send u the nupkg and u upload it by your own to nuget.org

To answer the possible quations why I would like to mention u as owner and author is simple:
Microsoft mentions [here ](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package) that:

```xml
<!-- Authors contain text that appears directly on the gallery -->
        <authors>Dejana Tesic, Rajeev Dey</authors>

        <!-- 
            Owners are typically nuget.org identities that allow gallery
            users to easily find other packages by the same owners.  
        -->
        <owners>dejanatc, rjdey</owners>
```

So the idea of the **owner** would be, that users can search your name on nuget and it would be possible to find other libraries of u. Another possibility would be, that I'll be the owner and people can search my name. Sooner or later i will provide more and more Libraries.
Since you are the original **author** of the library there should be no question about this shouldn't be?

Please let me know what u think about this.

</div>

**Comment by ColinH** [comment]
Thank you for your initiative, we are happy for every packet manager our libraries are made available through! And we are happy if you take care of the details - there are too many packet managers, Linux distributions and similar out there for us to keep up with, so our preferred way is for somebody more familiar with a particular management system to create, submit and maintain an entry.

**Comment by domi516** [comment]
Hi again,

I just want to give an update.
I've pushed the package on nuget: 
https://www.nuget.org/packages/Pegtl/3.2.2

I've mentioned you as author and me as the owner of the package. So I may take care about questions concerning the package :)

**Comment by d-frey** [comment]
Version 3.2.2 should be listed as licensed with the MIT license, future versions will be licensed with BSL-1.0. Also, if possible, we prefer the package name to be PEGTL or pegtl, not Pegtl.

Thanks for taking care of packaging 😊

**Comment by domi516** [comment]
oh ok, I've written to the support.
Because of the license, I've taken the license file from you? In the text of your reposiroty is the boost license:

> Boost Software License - Version 1.0 - August 17th, 2003
> 
> Permission is hereby granted, free of charge, to any person or organization
> obtaining a copy of the software and accompanying documentation covered by
> this license (the "Software") to use, reproduce, display, distribute,
> execute, and transmit the Software, and to prepare derivative works of the
> Software, and to permit third-parties to whom the Software is furnished to
> do so, all subject to the following:
> 
> The copyright notices in the Software and this entire statement, including
> the above license grant, this restriction and the following disclaimer,
> must be included in all copies of the Software, in whole or in part, and
> all derivative works of the Software, unless such copies or derivative
> works are solely in the form of machine-executable object code generated by
> a source language processor.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
> IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
> FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
> SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
> FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
> DEALINGS IN THE SOFTWARE.

https://github.com/taocpp/PEGTL/blob/main/LICENSE_1_0.txt


So has it to be changed?

**Comment by d-frey** [comment]
Yes, we just recently changed the license. The repository reflects the work-in-progress next release, we are currently debating whether that will be 3.3.0 or 4.0.0. But licenses can change, so each version of a package needs to stick with the license at the time the version was released.

**Comment by d-frey** [comment]
Another small thing you might want to work on: We list packages via Repology. See https://github.com/taocpp/PEGTL/blob/main/doc/Installing-and-Using.md#installation-packages

Repology does not seem to know about nuget, see https://repology.org/repositories/statistics

Maybe, if you are interested in promoting nuget, you want to work with the Repology-folks to scan nuget packages as well.
