### ISSUE TITLE
Relax filesystem requirement

### ISSUE THREAD

**Issue by stijnfrishert** [taocpp/PEGTL#299]
I would love to use PEGTL to parse some simple expressions, but the company I work with has a macOS deployment target that predates the filesystem library in std.

I realize we could use boost filesystem, but:
  a) The PEGTL Vcpkg package doesn't have that as a feature flag (can I request that here, or over at vcpkg?)
  b) We don't really need filesystem support at all.

I am unsure what PEGTL uses the filesystem for, I suspect reading expressions from disk, but that seems like a harsh requirement for people that just want to convert some a string into an ast.

Is it possible to put functionality that uses the filesystem behind a define?

**Comment by ColinH** [comment]
You should be able to build without `std::filesystem` and `boost::filesystem` by cherry-picking which parts of the PEGTL you include instead of using the catch-all `tao/pegtl.hpp`. As long as you avoid the file reading inputs you should be fine.

**Comment by stijnfrishert** [comment]
Bit of a late reaction, but thanks! I think that's enough for me to move forward with this :)
