### ISSUE TITLE
Plans for releasing PEGTL 3.3.0?

### ISSUE THREAD

**Issue by hartwork** [taocpp/PEGTL#300]
Hi PEGTL!

The [USBGuard project](https://usbguard.github.io/) has a copy of PEGTL 3.2.0 bundled at https://github.com/USBGuard/usbguard/tree/master/src/ThirdParty as of today. I saw that there is a release 3.2.2 and apparently [3.3.0 upcoming](https://github.com/taocpp/PEGTL/commit/8fb7915e224b6de522bf92555497427dbfd408b9) with [54 commits after 3.2.2 today](https://github.com/taocpp/PEGTL/compare/3.2.2...main).

I'd like to ask what your plans are for releasing 3.3.0 and also whether there are any source-level incompatibilities or pitfalls that USBGuard should watch out for, when updating PEGTL 3.2.0 to 3.2.2 or 3.3.0. (I'm technically not a member of USBGuard, but I consider opening  a related pull request.)

Thanks and best, Sebastian

**Comment by ColinH** [comment]
Hi Sebastian! We apply semantic versioning, meaning that you should not encounter any source-level incompatibilities within a major version. In particular updating within 3.x.y should not break anything.

One caveat is that we are slightly less strict with semantic versioning and compatibility for everything in the `contrib` folder, although we try to keep breaking changes to a minimum there, too.

We don't currently have any plans for a version 3.3.0, however I have started a major refactoring of the PEGTL input classes that is wildly incompatible and will result in a version 4.0.0.

**Comment by hartwork** [comment]
Hi @ColinH, thanks for your reply! I'll create a [pull request](https://github.com/USBGuard/usbguard/pull/521) to update to 3.2.2 then. (Let's maybe keep this ticket open so that other can find it more easily?)

**Comment by ColinH** [comment]
There is a new version 3.2.3 that fixes a static_assert with some recent versions of MSVC.

**Comment by hartwork** [comment]
@ColinH thanks for the fix and letting me know! :+1:
