### ISSUE TITLE
static_assert and two phase name lookup in demangle

### ISSUE THREAD

**Issue by NelsonEloi** [taocpp/PEGTL#301]
Good day PEGTL,

With the latest version of MSVC (x86 msvc v19.latest) the static_assert inside the demangle funcion fires during phase one when you don't have a type.

Link with reproduction

https://godbolt.org/z/hd9qPhY1W

Thank you very much and all the best
Nelson

**Comment by ColinH** [comment]
Is this the same as #296 ?

**Comment by NelsonEloi** [comment]
Yes its the same thing, I didn't notice it was reported already.

I think the reason is because T isn't useat all in the function the compiler validades during phase 1.

If you some how use T in the static_assert you can remove the error:

Something like https://godbolt.org/z/cWsaGzh6n 
Although that isn't  complete solution.

Thank you very much
Nelson

**Comment by ColinH** [comment]
Thanks, that explained how to fix it.

**Comment by ColinH** [comment]
Version 3.2.3 contains a fix.
