### ISSUE TITLE
[Git main] Merge conflict markers in file "doc/Changelog.md"

### ISSUE THREAD

**Issue by hartwork** [taocpp/PEGTL#302]
Commit 8de3badf79d4331ec769a57a2fe7f92c1aa7f4b1 introduced merge conflict markers into `doc/Changelog.md` that are still present. Are you aware?

**Comment by ColinH** [comment]
Missed that one somehow, thanks!

**Comment by hartwork** [comment]
Thanks for the fix! :+1:
