### ISSUE TITLE
How do I capture each substring at run time

### ISSUE THREAD

**Issue by w4454962** [taocpp/PEGTL#304]
`	

        struct type_name: name {};
	struct type_parent_name : type {};
	struct type_extends : if_must<key_type, space, type_name, sor<key_extends, ERR("ERROR_EXTENDS_TYPE")>, space, sor<type_parent_name, ERR("ERROR_EXTENDS_TYPE")>> {};

        template< typename Rule >
	struct check_action {};

	template<> 
	struct check_action<type_extends> {
		template< typename ActionInput >
		static void apply(const ActionInput& in, jass_state& s) {
			std::string str= in.string();
                }
        };
`

How to get the `type_name` and `type_parent_name` from `const ActionInput& in` ?

I don't want to write many applys. Is there a ready-made capture list?

**Comment by w4454962** [comment]
ActionInput need `const std::vector<std::string_view>& sub_string_view()`  and  `const ActionInput& get_parent_input()` method  How can i do ?

**Comment by ColinH** [comment]
> I don't want to write many applys.

Implementing many actions might be inevitable. Unless you add some intermediate layer, which could also be the parse tree from `tao/pegtl/contrib/parse_tree.hpp`.

> Is there a ready-made capture list?
> ActionInput need `const std::vector<ActionInput>& get_childs_input()`

That would require additional book-keeping which would be rather costly if it automatically kept the capture of every sub-rule. This cost should only be paid when and where necessary.

You might be able to set up some vector in the states, and a simple action that gets applied to multiple rules that merely pushes some information on to the vector, and then do all the actual processing in the action for the enclosing rule.

> and `const ActionInput& get_parent_input()` method. How can i do?

I don't get the intended semantics. What should `get_parent_input()` return?

Btw, the default case of `check_action< Rule >` should use `tao::pegtl::nothing< Rule >` as public base class.

**Comment by w4454962** [comment]
OK, I know what to do. I'll use ` parse_tree `  and rewrite 'transform' to complete
thank you
