### ISSUE TITLE
MSVC:  error C2338: static_assert failed: 'internal::dependent_true< T > && ( begin != std::string_view::npos )

### ISSUE THREAD

**Issue by matbech** [taocpp/PEGTL#308]
With MSVC Version 17.2.0 Preview 2.0
```
   static_assert( internal::dependent_true< T > && ( begin != std::string_view::npos ) );
```

```
 error C2338: static_assert failed: 'internal::dependent_true< T > && ( begin != std::string_view::npos )
```
File: taocpp-json\json\external\PEGTL\include\tao\pegtl\demangle.hpp(147,49)

It seems to be related to issue https://github.com/taocpp/PEGTL/issues/296 and https://github.com/taocpp/PEGTL/issues/301

The dependent_true<T> workaround doesn't seem to work any longer.

**Comment by d-frey** [comment]
Have you filed a bug-report with Microsoft? This is clearly their problem! (And it's a preview, so you should report it now!)

**Comment by d-frey** [comment]
I reported the bug to Microsoft: https://developercommunity.visualstudio.com/t/__FUNCSIG__-evaluates-to-a-type-erased-v/1695835

**Comment by matbech** [comment]
Thank you. Much appreciated. I have up-voted it.
