### ISSUE TITLE
data type of input? byte? character?

### ISSUE THREAD

**Issue by brouhaha** [taocpp/PEGTL#316]
The "Inputs and Parsing" doc tells me everything I might want to know about input _except_ the actual data type of the smallest atomic unit of input to the parser. Is it a byte (uint8_t)? Or a character, with some encoding, that might be more than one byte or even a variable number of bytes (e.g., UTF-8)?
I plan to use mmap_input on potentially very large files (gigabytes and up), and they are a mix of ASCII and binary, which I want to deal with strictly as uint8_t (or equivalently, 8-bit characters). Is that what I'll get by default?

**Comment by skyrich62** [comment]
Hi,
The answer to your question depends greatly on the parsing rules you use.  All of the "ascii" rules are byte oriented.
However the UTF-16 and UTF-32 rules are 2- and 4- byte oriented.

In other words, it's up to you by choosing the appropriate grammar rules to determine how to interpret the input bytestream.

**Comment by ColinH** [comment]
On a technical level the inputs currently use `const char *` to keep track of the input data, however, as mentioned by @skyrich62, this does not preclude some of the rules as interpreting the input as consisting of larger integral values.

Consequently using the PEGTL's `mmap_input` will also treat the input as sequence of `char`, however that does not mean anything and you can just as well only use the `uint8` rules that interpret the input bytes accordingly.

**Comment by brouhaha** [comment]
Thanks! That's very helpful. It confirms that PEGTL should work fine for my use case.
