### ISSUE TITLE
Feature Request: Add defines to exclude headers to improve compile time

### ISSUE THREAD

**Issue by matbech** [taocpp/PEGTL#320]
To reduce compile times, it would be nice to exclude certain headers which aren't used by setting some defines. 

When profiling the compile time with MSVC using [Compile Score](https://github.com/Viladoman/CompileScore) I noticed that the following includes:
https://github.com/taocpp/PEGTL/blob/main/include/tao/pegtl.hpp#L21
#include "pegtl/read_input.hpp"
#include "pegtl/file_input.hpp"
take a significant amount of time (tons of STL headers like filesystem,chrono, etc are pulled in) but none of this functionality is used in our code base.

A possible solution may look like this:
```
#ifndef TAOCPP_PEGTL_EXCLUDE_READINPUT
#include "pegtl/read_input.hpp"
#endif
```

**Comment by ColinH** [comment]
Would it work if, instead of including `tao/pegtl.hpp`, you cherry-pick the includes that you need?

**Comment by ColinH** [comment]
Oh. I see :-)

Then I have to look in to how cumbersome it would be to let taoJSON only use cherry-picked PEGTL headers...

**Comment by ColinH** [comment]
Most parts of taoJSON already did "the right thing" by including only the necessary headers instead of `tao/pegtl.hpp`. A small patch I just pushed to taoJSON finishes the job.
