### ISSUE TITLE
Does "pegtl" support the operation of binary data serialization/deserialization?

### ISSUE THREAD

**Issue by w4454962** [taocpp/PEGTL#322]
If yes, have you provided any demonstration examples? Thank you

I only saw the parsing of "protobuf" syntax, but did not find a real example of parsing and mapping binary data blocks.

**Comment by ColinH** [comment]
The PEGTL is for parsing, so it can't help you with serialisation, regardless of text or binary formats.

For deserialisation I'd say the PEGTL isn't especially well suited to binary data, however (a) we have used the PEGTL infrastructure in our taoJSON library for parsing binary JSON-like data formats (CBOR, UBJSON and MsgPack) and (b) support for binary data will be improved as soon as I get around to finishing the back-porting of some experiments to the main branch.

You can look at the taoJSON code here: https://github.com/taocpp/json/tree/main/include/tao/json and If you want to try parsing binary data with the PEGTL then please feel free to contact us here, both for questions and for feedback, it's always useful to see how other people use the library.

**Comment by w4454962** [comment]
Yes, I am considering using "pegtl" for binary deserialization parsing. Binary data blocks are also composed of different rules, and there are two parsing methods

1. Describe the specified binary block by parsing the "protobuf" syntax, and use a virtual machine like method to complete data deconstruction

2. The rules for defining binary blocks with c++templates are parsed through template expansion.


The first method may cause some consumption, but supports hot update

The second method may be zero consumption, but each rule modification requires recompilation, and templating may not be suitable for the hash table structure
