### ISSUE TITLE
Order independence of rules

### ISSUE THREAD

**Issue by Qbort** [taocpp/PEGTL#335]
Say I have a set of rules `rule1` `rule2` and `rule3`. I want to be able to match these rules one or zero times and I don't care about the sequence. The important thing is that each rule should only be matched a maximum of 1 time and minimum of 0 i.e. the below will not work because while it will achieve order independence, the rules can be mached any number of times:
```c++
struct myRule : star< sor< rule1, rule2, rule3 > > {};
```

In my current understanding of PEGTL, I could write something like the below, where I cover all the permutations (3! = 6 permutations)
```c++
struct myRule : sor< 
                    seq< opt<rule1>, opt<rule2>, opt<rule3> >,
                    seq< opt<rule1>, opt<rule3>, opt<rule2> >,
                    seq< opt<rule2>, opt<rule1>, opt<rule3> >,
                    seq< opt<rule2>, opt<rule3>, opt<rule1> >,
                    seq< opt<rule3>, opt<rule1>, opt<rule2> >,
                    seq< opt<rule3>, opt<rule2>, opt<rule1> >
                 > {};
```

This is okay for 3 rules, but what about 10 rules? That gets unwieldly with 10! = 3628800

Is there a more simplified form I am missing? If not, could one possibly be added?

**Comment by ColinH** [comment]
This is definitely a new use case, i.e. one we have never seen, and there is no built-in way to handle it. One possibility would be to enforce the zero-or-once in the actions; perhaps not the most elegant solution, but still better than enumerating all permutations. It might also be easy to create a special rule for this case. Please send us anything you come up with if you write something, I'll look into this in more detail sometime soon.

**Comment by Qbort** [comment]
Thanks. I will use states and actions for the time being and add the logic to throw parse error as required.

I'll also have a look to see if there is any chance I can get a special rule made here - however my c++ templating skills are still in development so it is unlikely I'll succeed any time soon :)

**Comment by ColinH** [comment]
In commit https://github.com/taocpp/PEGTL/commit/08bf50af8b90ee69c016d7ca8188d3308ba13eaf I added an example with two random order rules, one for "all rules must appear once in random order", and one that makes each rule occurrence optional. Both rules do not attempt to match sub-rules after they match, and don't check for further repetitions of the sub-rules after reaching a success condition.

**Comment by Qbort** [comment]
Sorry for the delay. Thank you for the example. 

I guess this does not work with PEGTL 3.x? When building on msvc with c++17 and PEGTL 3.x I get the following error:
```
random_order.cpp(38):  error C2059: syntax error: 'template'
 ```
 
https://github.com/taocpp/PEGTL/blob/08bf50af8b90ee69c016d7ca8188d3308ba13eaf/src/example/pegtl/random_order.cpp#L43

**Comment by ColinH** [comment]
At this point 3.x and main have not diverged too much yet, if you change `auto_rewind` to `mark` in line 43 it should work.

**Comment by Qbort** [comment]
Thanks it works  👍

**Comment by ColinH** [comment]
Great. I'll close this issue for now, but feel free to continue this discussion and/or re-open if you have any further questions.

**Comment by ColinH** [comment]
> In commit [08bf50a](https://github.com/taocpp/PEGTL/commit/08bf50af8b90ee69c016d7ca8188d3308ba13eaf) I added an example with two random order rules, one for "all rules must appear once in random order", and one that makes each rule occurrence optional. Both rules do not attempt to match sub-rules after they match, and don't check for further repetitions of the sub-rules after reaching a success condition.

@Qbort I just found a bug in line 46 of the linked commit, the rewind mode is not correct and can lead to wrong parsing behaviour.

The easiest fix is to use `rewind_mode::required` when matching the sub-rules.

The slightly more efficient fix is to use an approach similar to that of `sor`, see https://github.com/taocpp/PEGTL/commit/44a45624f2b6723904c887e2fbd625dffd4a1171
