### ISSUE TITLE
list_tail<> invokes action for trailing separator twice?

### ISSUE THREAD

**Issue by gitamohr** [taocpp/PEGTL#340]
I'm brand-new to PEGTL so please let me know if I'm misunderstanding this.  My grammar is just `list_tail<identifier, one<'/'>>`, but my action for the `one<'/'>` is invoked twice in case of a trailing separator; I would expect it to be just once.  Here's my test; I'm using version 2.8.3.
```
using namespace tao::pegtl;

struct path_sep : one<'/'> {};
struct path : list_tail<identifier, path_sep> {};

template <class Rule>
struct path_action : nothing<Rule> {};

template <>
struct path_action<path> {
    template <class Input>
    static void apply(Input const &in) {
        printf("  - path: '%s' @ %s\n", in.string().c_str(), to_string(in.position()).c_str());
    }
};

template <>
struct path_action<path_sep> {
    template <class Input>
    static void apply(Input const &in) {
        printf("  - separator: '%s' @ %s\n", in.string().c_str(), to_string(in.position()).c_str());
    }
};

void test() {
    for (std::string test_str: {"no/trailing", "yes/trailing/"}) {
        printf("parse '%s' {\n", test_str.c_str());
        parse<path, path_action>(string_input<> { test_str, "<code>" });
        printf("}\n");
    }
}

/*** test() output: ***/

parse 'no/trailing' {
  - separator: '/' @ <code>:1:2(2)
  - path: 'no/trailing' @ <code>:1:0(0)
}
parse 'yes/trailing/' {
  - separator: '/' @ <code>:1:3(3)
  - separator: '/' @ <code>:1:12(12)
  - separator: '/' @ <code>:1:12(12)
  - path: 'yes/trailing/' @ <code>:1:0(0)
}
```
I was surprised to see three "separator"s for `yes/trailing/`.  Is there a bug in my code, or in PEGTL, or is this expected?  Thanks!

**Comment by ColinH** [comment]
The `list_tail` rule is implemented as

```
template< typename Rule, typename Sep >
using list_tail = seq< Rule, star< Sep, Rule >, opt< Sep > >;
```

so it's clear why the action for a trailing separator is called twice.

(Once when `Sep` matches during the final attempt of the implicit `seq< Sep, Rule >` inside of `star`, and once in `opt< Sep >` after backtracking to before the `Sep` in the `seq`.)

@d-frey I suppose we should consider this as undesired behaviour and therefore a bug...

**Comment by skyrich62** [comment]
Hi,
In the case of (alice, bob, carol) vs. (alice, bob, dan), you should re-factor you grammar such that prefix to rules are separated like this:

```
struct prefix : seq<alice, bob> { };
struct group: seq< prefix, sor< carol, dan> > { };
```

This way, backtracking is eliminated.   It is also possible to use the at<> rule to do infinite look-ahead, which doesn't invoke actions.

**Comment by ColinH** [comment]
What @skyrich62 said is what we usually go for, factor out common prefixes to reduce the problem.

That said, in the case of `list_tail` it's still a bug because the double invocation is a side-effect of how the rule is implemented, and not the documented behaviour that a user should expect.

Looking through the PEGTL rule definitions I found a few other rules that might need to be treated for the same problem:
```
list.hpp:   using list = seq< Rule, star< Sep, Rule > >;  // Is it ok to call an action for Sep when it's not followed by Rule?
list_tail.hpp:   using list_tail = seq< Rule, star< Sep, Rule >, opt< Sep > >;  // This issue.
list_tail_pad.hpp:   using list_tail_pad = seq< Rule, star< pad< Sep, Pad >, Rule >, opt< star< Pad >, Sep > >;  // Same as list_tail<>.
rep_min.hpp:   using rep_min = seq< rep< Min, Rule, Rules... >, star< Rule, Rules... > >;  // Same as list<>
```

**Comment by gitamohr** [comment]
Ah I see, thank you both!

**Comment by skyrich62** [comment]
It seems that "star<Sep, Rule>" is insufficient for the expected purposes.  Perhaps a bit of look-ahead could be used to avoid calling the action of Sep, if not followed by Rule?

star< at<Sep, Rule>, Sep, Rule > ??

--Rich

**Comment by gitamohr** [comment]
Thanks again @skyrich62 and @ColinH !  Here's a probably naive question if you'll indulge me. It seems like something that works like `at<whole_grammar>` could in principle build a list of the actions to apply as it parses, without applying them, deleting those for rules that are backtracked.  Then they could be applied once at the end, without invoking any actions for rules that were backtracked.  Does that make sense?  Is something like that possible today in PEGTL?

Writing the grammar in a way that minimizes backtracking would still be important, and there would be overhead associated with building the list.  But for smaller languages & inputs it seems appealing, at least from my green perspective.  Cheers!

**Comment by ColinH** [comment]
@gitamohr Deferring all actions until later is something that I had looked at briefly as it could be useful while developing a grammar or for debugging, but it's not _quite_ as easy as it appears at first.

**Comment by ColinH** [comment]
This is now fixed on the main branch. It required a new form of `star` called `star_partial` which is now used for `list_tail`. There might be some related-but-different future changes to `list` and `rep_opt` that will be discussed elsewhere.

**Comment by gitamohr** [comment]
Cool, thank you!
