### ISSUE TITLE
MIT License in release tarball vs. BSL-1.0 in Git Repository

### ISSUE THREAD

**Issue by mdb571** [taocpp/PEGTL#363]
I've noticed a license inconsistency in the PEGTL repository. The tarball for v3.2.7 downloaded from [here](https://github.com/taocpp/PEGTL/archive/refs/tags/3.2.7.tar.gz) contains the MIT License.

```bash
[zulu@debian PEGTL-3.2.7]$ cat LICENSE | head -n1
The MIT License (MIT)
```

However #270 & c7630f1649906daf08b8ddca1420e66b542bae2b indicates a license change occured. Could you please clarify which license applies for the project

**Comment by d-frey** [comment]
The latest official release is still based on the 3.x-branch, in which the PEGTL was still MIT licensed. The change to BSL-1.0 happened on the main branch and will lead to a new major release, but no official releases have been made yet. Yeah, it's a long time in the making...
