### ISSUE TITLE
MSYS2 environment is not considered in tests

### ISSUE THREAD

**Issue by Totto16** [taocpp/PEGTL#365]
3 Tests fail on msys, since wrong file names are used in those cases.

`src/test/pegtl/file_file.cpp`
`src/test/pegtl/file_mmap.cpp`
`src/test/pegtl/file_read.cpp`

In this code MSYS isn't considered and handled incorrectly

`src/test/pegtl/verify_file.hpp:11`
```cpp
#if defined( _MSC_VER )
#define TAO_PEGTL_TEST_FILENAME u"src/test/pegtl/file_äöü𝄞_data.txt"
#else
#define TAO_PEGTL_TEST_FILENAME "src/test/pegtl/file_äöü𝄞_data.txt"
#endif
```

I think fixing this is easy, just detect msys2 and use the correct string format there.

See e.g. [this CI run](https://github.com/mesonbuild/wrapdb/actions/runs/10333226401/job/28605345845) as example

**Comment by ColinH** [comment]
That does sound like an easy fix, however I'm not sure in which direction, and I don't have an environment to test it myself. In other words, can you please let me know whether

```c++
#if defined( _MSC_VER ) || defined( __MSYS__ )
#define TAO_PEGTL_TEST_FILENAME u"src/test/pegtl/file_äöü𝄞_data.txt"
#else
#define TAO_PEGTL_TEST_FILENAME "src/test/pegtl/file_äöü𝄞_data.txt"
#endif
```
or
```c++
#if defined( _MSC_VER ) && !defined( __MSYS__ )
#define TAO_PEGTL_TEST_FILENAME u"src/test/pegtl/file_äöü𝄞_data.txt"
#else
#define TAO_PEGTL_TEST_FILENAME "src/test/pegtl/file_äöü𝄞_data.txt"
#endif
```
is needed?

**Comment by ColinH** [comment]
Note to self: https://www.msys2.org/wiki/Porting/

**Comment by Totto16** [comment]
> That does sound like an easy fix, however I'm not sure what "the correct format" for MSYS2 is, and I don't have an environment to test it myself. In other words, can you please let me know whether
> 
> ```c++
> #if defined( _MSC_VER ) || defined( __MSYS__ )
> #define TAO_PEGTL_TEST_FILENAME u"src/test/pegtl/file_äöü𝄞_data.txt"
> #else
> #define TAO_PEGTL_TEST_FILENAME "src/test/pegtl/file_äöü𝄞_data.txt"
> #endif
> ```
> 
> or
> 
> ```c++
> #if defined( _MSC_VER ) && !defined( __MSYS__ )
> #define TAO_PEGTL_TEST_FILENAME u"src/test/pegtl/file_äöü𝄞_data.txt"
> #else
> #define TAO_PEGTL_TEST_FILENAME "src/test/pegtl/file_äöü𝄞_data.txt"
> #endif
> ```
> 
> is needed?

I am not entirely sure myself either, but I can test it, if msys support is panned a Ci would be helpful too, maybe I can contribute one
