### ISSUE TITLE
GCC crashes on deduction guide

### ISSUE THREAD

**Issue by catsidhe** [taocpp/PEGTL#373]
Possibly a compiler regression. However it might still be worth taking a look.

GCC Arch Linux package version 14.2.1+r134+gab884fffe3fc-1
```
$ gcc --version 
gcc (GCC) 14.2.1 20240910
```
Trying to use `file_input`:
```
/home/foo/bar/pegtl/include/tao/pegtl/mmap_input.hpp:45:13: internal compiler error: Segmentation fault
   45 |    explicit mmap_input( Ts&&... ) -> mmap_input<>;
      |             ^~~~~~~~~~
0x21a922a internal_error(char const*, ...)
```
The problem goes away when changing the deduction guide from:
```cpp
   template< typename... Ts >
   explicit mmap_input( Ts&&... ) -> mmap_input<>;
```
to:
```cpp
   template< tracking_mode = tracking_mode::eager, typename... Ts >
   explicit mmap_input( Ts&&... ) -> mmap_input<>;
```
Previous GCC build did not crash. Clang works either way.

**Comment by ColinH** [comment]
This does look like a compiler bug, seeing as even the example in the C++ standard completely omits a defaulted template argument. What does GCC 14.2 say to this alternative?

```c++
   template< typename... Ts >
   explicit mmap_input( Ts&&... ) -> mmap_input< tracking_mode::eager, eol::lf_crlf >;
```

**Comment by catsidhe** [comment]
Unfortunately, still crashes with your alternative.

Admittedly, my fix is not correct either, it probably just makes the deduction guide not to be considered. If I change it to `template< typename, typename... Ts >` it also stops crashing. So yes, likely a compiler bug.

I've never used deduction guides in my own code, and not quite sure what this one is for. Is it to avoid having to specify `<>` to use the default parameters? Even it I delete the deduction guide entirely, everything continues to compile for me, including code like `auto mmi = peg::mmap_input{std::filesystem::path{}};`. Maybe it's the standard version specific? (I use std=c++23)

If you believe there are no issues with the deduction guide, I think it's safe to close this. I'll file the compiler bug if it continues to happen in newer GCC builds.

**Comment by catsidhe** [comment]
I found that it crashes only when instantiating a subclass and only in C++23 or above.

```cpp
#include <tao/pegtl.hpp>

int main() {
  tao::pegtl::mmap_input mi{std::filesystem::path{}}; // always works
  tao::pegtl::file_input fi{std::filesystem::path{}}; // works with -std=c++20, crashes GCC with -std=c++2b
}
```

**Comment by ColinH** [comment]
Sounds like it's safe to assume a GCC bug with newer C++ standards and leave it at that.
