### ISSUE TITLE
Add cmake option for disabling testing & examples

### ISSUE THREAD

**Issue by feliwir** [taocpp/PEGTL#54]
Hello, 
I am using PEGTL as a submodule for my own repository and link it by using "cmake_add_subdirectroy" (which works perfectly fine). The annoying part is that this will add all of the PEGL examples & tests to my own project. Currently there is no cmake option to disable this. I'd recommend something like this:
```option(BUILD_TESTS "Wether or not to build PEGL test cases"  TRUE)```,
which would build the tests if not explicitly disabled before.

**Comment by d-frey** [comment]
I added two options, one for tests, one for the examples. Please see if it works for you and solves your issue, re-open when necessary.

Also, since this is the first time I'm working with CMake, please point out anything that you feel could be improved. Thanks. :)

**Comment by feliwir** [comment]
Yep this is exactly what i was looking. Maybe I'd prefix the options with PEGTL_ (= PEGTL_BUILD_EXAMPLES etc.), so there is no conflict with variables from other cmake projects. For example it is done like this in GLFW: http://www.glfw.org/docs/latest/build_guide.html#build_link_cmake_source

Thanks for your fix 👍

**Comment by d-frey** [comment]
Good idea, I've added the prefixes. Thanks.
