### ISSUE TITLE
build with mingw-w64 failed .

### ISSUE THREAD

**Issue by 11nk** [taocpp/PEGTL#57]
gcc do not support _assume .

**Comment by d-frey** [comment]
Does changing the condition of the `#if` in [the line before]((https://github.com/taocpp/PEGTL/blob/26df6aa2d6e582d098b85478a34d4487de8c82c5/include/tao/pegtl/internal/raise.hpp#L38)) from `_WIN32` to `_MSC_VER` help?

**Comment by 11nk** [comment]
yes `#if defined( _WIN32 ) && defined(_MSC_VER)` will be work .

**Comment by d-frey** [comment]
Great! (I already committed a simplified version, as testing `_WIN32` is not needed in this case)

Also, we are looking into ways to extend the `.appveyor.yml` to test with MinGW to prevent future problems for MinGW users. Any help is appreciated...

**Comment by d-frey** [comment]
(Thinking about it, it actually was a bug, not an enhancement)
