### ISSUE TITLE
'template argument 3 is invalid'

### ISSUE THREAD

**Issue by Ironholds** [taocpp/PEGTL#58]
Using [a modified version](https://github.com/Ironholds/piton/blob/master/src/peg_test.cpp#L26-L29) of the 'ID and sum comma-separated digits' example:

```
peg_test.cpp:29:68: error: template argument 3 is invalid
                            seq< plus< D >, opt< dot, star< D > > > > {};
                                                                    ^
In file included from ../inst/include/pegtl/internal/action.hpp:9:0,
                 from ../inst/include/pegtl/internal/rules.hpp:7,
                 from ../inst/include/pegtl/ascii.hpp:11,
                 from ../inst/include/pegtl.hpp:10,
                 from peg_test.cpp:3:
```

C++11 via GCC 4.9.3; works fine on clang, however!

**Comment by ColinH** [comment]
Just looked at it briefly and I can't see anything wrong, also GCC 4.9 is one of the compilers that we test every commit with, see the Travis-CI config. Does the error also occur when you remove the Rcpp header file, and the code beneath the two namespaces?

**Comment by Ironholds** [comment]
Goood question. I'll find out!

**Comment by Ironholds** [comment]
Yep; looks like some conflict somewhere. Now resolved - thank you!

**Comment by ColinH** [comment]
Glad to hear - happy hacking :-)
