### ISSUE TITLE
TAOCPP_PEGTL_KEYWORD does not compile

### ISSUE THREAD

**Issue by agustingianni** [taocpp/PEGTL#63]
I'm trying to use `TAOCPP_PEGTL_KEYWORD` but it does not compile. I think the macro is missing something.

This is the offending code.
```
struct ARRAY : TAOCPP_PEGTL_KEYWORD("array") {};
```
I'm using version 2.0 installed via brew on macOS.

The compiler output can be found here: https://gist.github.com/agustingianni/2503c7f83c0ff9617bda0e74a51d52d5

**Comment by d-frey** [comment]
D'oh! Yes, I missed two things: Writing a testcase for `TAOCPP_PEGTL_KEYWORD` and the fact that the macro uses empty intermediate values. And `keyword<>` is not valid, as a keyword always needs to have at least one character (unlike the empty string, which is allowed). I'll fix it in a minute...

**Comment by agustingianni** [comment]
Thank you very much!
