### ISSUE TITLE
Allow literal strings for pegtl::string

### ISSUE THREAD

**Issue by lambdafu** [taocpp/PEGTL#72]
Allowing

```
pegtl::string<"Hello, ">
```
would obviously be simpler than

```
pegtl::string<'H', 'e', 'l', 'l', 'o', ',', ' '>
```

but implementing this is a chore. I am not versed enough in C++ to know if upcoming standard versions make it simpler, but for now I found a workaround with boost.  This issue is a placeholder so others can find it until pegtl supports it natively (so feel free to close the issue if it is not a priority for now).

```
  #include <boost/metaparse/string.hpp>

  template<typename T>
  struct literal_string {};

  template<char... Cs>
  struct literal_string<boost::metaparse::string<Cs...> > : pegtl::string<Cs...> {};

  #define STRING(str) literal_string< BOOST_METAPARSE_STRING(str) >

  struct prefix
     : STRING("Hello, ")
   {};

```

**Comment by d-frey** [comment]
We already have that, it's [`TAOCPP_PEGTL_STRING`](https://github.com/taocpp/PEGTL/blob/master/doc/Rule-Reference.md#taocpp_pegtl_string--):

    struct prefix
      : TAOCPP_PEGTL_STRING( "Hello, " )
    {};

**Comment by lambdafu** [comment]
Fantastic, somehow this escaped my attention! :heart:
