### ISSUE TITLE
unexpected behaviour of discard (or bug?)

### ISSUE THREAD

**Issue by lambdafu** [taocpp/PEGTL#95]
Hi,

I found that discard breaks input matching in the action.  This seems to be a bug?  Below you can find a test case that shows two behaviours.  I'd have expected either to work.

The guts of it is in this rule:
```
struct word1 : seq<discard, bytes<4>> {};
```

In the action, I try to match the four byte input string, but find that the discard (which should throw away the three preceeding characters) throws away the first three characters of `bytes<4>`. 

```
$ ./discard-test
Unexpected:
INPUT: 3/3: one
INPUT: 4/4: vase
WORD: e
INPUT: 3/3: two
INPUT: 4/4: pots
WORD: s
INPUT: 0/3: 

Expected:
INPUT: 3/3: one
INPUT: 4/4: vase
WORD: vase
INPUT: 3/3: two
INPUT: 4/4: pots
WORD: pots
INPUT: 0/3: 
```

```
#include <tao/pegtl.hpp>
#include <stringstream>
#include <iostream>

using namespace tao::pegtl;

struct word1 : seq<discard, bytes<4>> {};
struct grammar1 : star<discard, bytes<3>, word1> {};

struct word2 : seq<bytes<4>> {};
struct grammar2 : star<discard, bytes<3>, discard, word2> {};

template <typename Rule>
struct xaction : nothing<Rule> {};

template <>
struct xaction<word1> {
  template <typename Input>
  static void apply(const Input& in) {
    std::string str = in.string();
  std:
    std::cerr << "WORD: " << str << "\n";
  }
};

template <>
struct xaction<word2> : xaction<word1> {};

int main(int argc, char* argv[]) {
  std::stringstream data;
  data << "onevasetwopots";
  using reader_t =
      std::function<std::size_t(char* buffer, const std::size_t length)>;

  auto reader = [&data](char* buffer, const std::size_t length) mutable {
    std::streamsize sz = data.read(buffer, length).gcount();
    std::cerr << "INPUT: " << sz << "/" << length << ": ";
    std::cerr.write(buffer, sz);
    std::cerr << "\n";
    return sz;
  };
  std::cerr << "Unexpected:\n";
  buffer_input<reader_t> input1("reader", 1024, reader);
  parse<grammar1, xaction>(input1);

  std::cerr << "\nExpected:\n";
  data.clear();
  data.seekg(0, data.beg);
  buffer_input<reader_t> input2("reader", 1024, reader);
  parse<grammar2, xaction>(input2);
  return 0;
}
```

**Comment by d-frey** [comment]
I'm not sure that this is a bug, Colin will mark it as such if it is.

My thinking is that anytime you use `discard` all rules involving it may not return the correct result for the matched input fragment. In your example only an action for `bytes<4>` will work correctly, the input for `seq<discard, ...>` will always be undefined.

@ColinH Could you clarify this in the documentation? Is it even allowed to access `input.string()` when the rule contains `discard`? Could we protect against that?

**Comment by lambdafu** [comment]
Your thinking does make sense in particular if one considers the case `seq<A, discard, B>` where `A` will be discarded.  I may have been tricked by the special case were `discard` is at the beginning of a sequence, which is not obviously illogical.

**Comment by d-frey** [comment]
It might not look illogical at the beginning, but think about what happens:

* `seq<discard, bytes<4>>` starts, the buffer is filled with 3 characters from before.
* `seq` remembers the beginning of the input by storing a `const char*` into the buffer.
* `seq` now calls the rules it contains, `discard` being the first one.
* `discard` now shifts the buffer (which might contain pre-read input) 3 characters to the left.
* `bytes<4>` reads 4 characters.
* `seq` now ends, the end of the input is now poining at the 4th character in the buffer.
* `seq`'s action now gets called with the remembered first character (which was the 3rd character in the buffer) to the last character (which is now the 4th character).
* You now see `e` as the input.

Looking at it this way is both logical, explains the result you are seeing and explains why `discard` may always trash the matched input.

**Comment by ColinH** [comment]
It's not really a bug, at least not in the code; `discard` modifies the buffer, so it doesn't play well, and shouldn't be used, together with any rules that remember positions in the input. Invoking actions remembers the position to know which portion of the input to pass to the action.

We will update the documentation to make it clearer, and I now have an idea on how to use a `static_assert` to prevent these shenanigans from happening in the first place, we'll have to see whether it works and whether it's not too strict.

**Comment by ColinH** [comment]
As expected the `static_assert` is too strict so we can't use it without some serious extensions to the core library; for now I'll clarify the restriction in the documentation.

**Comment by lambdafu** [comment]
Thanks everybody for the explanations, it is clear now!
