### ISSUE TITLE
Example abnf2pegtl2.cpp does not throw custom errors.

### ISSUE THREAD

**Issue by engelant** [taocpp/PEGTL#98]
I tried out the abnf2pegtl2.cpp example after I couldn't find out at which point the  `error_control` is passed trough the `tao::pegtl::parse_tree::parse` to `tao::pegtl::parse`, and it seems it just isn't. Therefor custom error messages are not thrown.

**Comment by d-frey** [comment]
True. I will fix it tomorrow, enhancing `parse_tree::parse` to accept a base class for the internally generated control class.
