### ISSUE TITLE
Accessing line length from file_input<>

### ISSUE THREAD

**Issue by engelant** [taocpp/PEGTL#99]
Today I tried to use the `file_input<> in` class to try to find out some information on the characters surrounding the byte position I've got from a thrown `parse_error`.
My goal is to create an error message like this:
```
[Error] ./test/testfile.js:2:14(58): Unexpected character in variable statement
>>> var Bar = 0xE var Foo;
                  ^
```
With the `parse_error` thrown I've got access to:

- byte
- byte_in_line
- line
- source

Do you have any suggestions on how to get the error's line's size?
Only thing I could imagine is using `in.bump()` with the error's offset, and then bump by 1 until eof, or `in.position.line() != e.positions().front().line` , but I can't seem to find a reset operator. Basicly I'm not able to iterate trogh the Input. What I tried out so far is:
```
auto err_pos = e.positions.front();
std::cout << "[ERROR] " << e.what() << std::endl;
std::cout << ">>> " << std::string(in.current(), err_pos.byte - err_pos.byte_in_line, err_pos.byte_in_line + 1 ) << std::endl;
std::cout << std::string(4 + err_pos.byte_in_line, ' ') << '^'<< std::endl;
```
But it obviously end with the first character of the parsed error.
Any suggestions?

**Comment by d-frey** [comment]
In order to support this properly, I implemented a new method on the input which internally creates another `memory_input` and *parses* the new input with an internal micro-grammar just to extract the current line. I think it should solve your use-case nicely and I've already used it for `abnf2pegtl2` to improve error reporting.

**Comment by engelant** [comment]
While this is a valid solution for a use case this becomes terrible as soon as the input is a single line.
This is why I asked about an numeric indicator for the line length. In my case this means I would try to define a "sane" output width (e.g. 40 chars), then check:

- line_length <= 40 -> just print the whole line 
- else -> extract a segment of 40 chars around the error's occurence (tbd)

While I certainly can extract this information from ``std::string.length` this solution seems a bit tackleing it in a roundabout way.

Now before I write anything stupid, is there an easy way to access the `position` of each offset of `file_input<> in` at random?

**Comment by d-frey** [comment]
I've refactored the API, with the returned `const char*`s it should be easy to access all characters individually, put limits on the length around the current position, etc.

**Comment by engelant** [comment]
I found a solution for my case, just sharing it:
```
catch (const parse_error& e) {
			const size_t ERROR_DISPLAY_SIZE = 40;
			auto input_size = in.size();
			auto err_pos = e.positions.front();
			
			size_t byte_line_end = (size_t) ((in.end_of_line(err_pos) - in.current())/sizeof(char)),
				byte_line_begin = err_pos.byte - err_pos.byte_in_line,
				line_size = byte_line_end - byte_line_begin;
			
			std::cout << "[ERROR] " << e.what() << std::endl;
			
			if (line_size <= ERROR_DISPLAY_SIZE) {
				std::cout << ">>> " << std::string(in.current(), byte_line_begin, line_size ) << std::endl;
				std::cout << std::string(2 + err_pos.byte_in_line, ' ') << "~~^~~" << std::endl;
			} else {
				size_t left_offset = 0;
				if ( (line_size - err_pos.byte_in_line) <= 10 ) {
					left_offset = byte_line_end - ERROR_DISPLAY_SIZE;
				} else if (err_pos.byte_in_line <= ERROR_DISPLAY_SIZE / 2) {
					left_offset = 0;
				} else {
					left_offset = err_pos.byte_in_line - ERROR_DISPLAY_SIZE / 2;
				}
				std::cout << "... " << std::string(in.current(), byte_line_begin + left_offset, ERROR_DISPLAY_SIZE ) << " ..." << std::endl;
				std::cout << std::string(2 + err_pos.byte_in_line - left_offset, ' ') << "~~^~~" << std::endl;
			}
		}
```
